apiVersion: v1
kind: Service
metadata:
  name: kuard-app-service
  namespace: default
  labels:
    app: kuard-app
    managed-by: deploypilot
spec:
  selector:
    app: kuard-app
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
